export type AIProviderType = 'openai' | 'grok' | 'google'

export interface AIConfig {
  provider: AIProviderType
  apiKey: string
  model?: string
}

export interface AIResponse<T = unknown> {
  success: boolean
  data?: T
  error?: string
}

export interface AIAnalysisResult {
  problemAnalysis: string
  strategy: string
  targetAudiences: string[]
  suggestedSources: string[]
  expectedContactTypes: string[]
}

export interface AIMessageResult {
  emailSubject: string
  emailBody: string
  contactFormMessage: string
  followUpMessage: string
  /** AI-suggested mapping of message content to form field names */
  formFieldMapping?: Record<string, string>
}

export interface ScrapeTarget {
  url: string
  domain: string
  rationale: string
  type: 'directory' | 'portal' | 'association' | 'media' | 'ngo' | 'company' | 'blog' | 'other'
  estimatedContacts: number
  /** URL of a detected contact form page (if known) */
  contactFormUrl?: string
  /** Whether the target has a detectable contact form */
  hasForm?: boolean
}

export interface TargetDiscoveryResult {
  targets: ScrapeTarget[]
}

// ── AI Search Criteria ───────────────────────────────────────────────────────

/** A family of related search queries generated by AI */
export interface SearchCriteriaFamily {
  /** Descriptive label for the query group (e.g. "Agencias marketing digital") */
  category: string
  /** Concrete search queries to execute (3-5 per family) */
  queries: string[]
  /** Why this family is relevant to the investigation */
  rationale: string
  /** Execution priority (1 = highest) */
  priority: number
}

/** Result of AI search criteria generation */
export interface AISearchCriteriaResult {
  families: SearchCriteriaFamily[]
  /** Estimate of how many domains these queries might surface */
  estimatedReach: number
}
