import type {
  AIProviderType,
  AIAnalysisResult,
  AIMessageResult,
  AIResponse,
  AISearchCriteriaResult,
  TargetDiscoveryResult,
} from '@core/types/ai.types'
import type { Contact } from '@core/types/contact.types'

export type ContactType = 'corporate' | 'individual' | 'institutional'

export interface CampaignBrief {
  contactType: ContactType
  affinityCategory: string
  affinitySubcategory: string
  language: string
  country: string
  consistency: number
  description: string
  reportLanguage: string
}

export interface CampaignReport {
  reportMarkdown: string
}

export interface AIProvider {
  analyzeCampaign(brief: CampaignBrief): Promise<AIResponse<CampaignReport>>
  analyzePrompt(prompt: string, consistency: number): Promise<AIResponse<AIAnalysisResult>>
  generateMessages(contact: Contact, context: string): Promise<AIResponse<AIMessageResult>>
  generateSearchTargets(brief: CampaignBrief): Promise<AIResponse<TargetDiscoveryResult>>
  generateSearchCriteria(brief: CampaignBrief): Promise<AIResponse<AISearchCriteriaResult>>
  testConnection(): Promise<AIResponse<{ model: string }>>
  /** Raw completion — returns the model's text response without any prompt wrapping. */
  evaluate(prompt: string): Promise<AIResponse<string>>
}

function buildCampaignReportPrompt(brief: CampaignBrief): string {
  const reportLang = brief.reportLanguage || 'English'
  return `You are a Senior Strategic Intelligence Analyst at a top-tier market research firm. Your task is to generate a comprehensive, highly professional campaign strategy report for a client.

CAMPAIGN BRIEF:
- Contact target type: ${brief.contactType === 'corporate' ? 'Corporate / Business entities' : brief.contactType === 'individual' ? 'Individual / Personal contacts' : 'Institutional / Government / NGO'}
- Primary affinity domain: ${brief.affinityCategory}
- Specific niche / subcategory: ${brief.affinitySubcategory}
- Target contact language: ${brief.language}
- Target country / region: ${brief.country}
- Search precision level: ${brief.consistency}/10 (${brief.consistency <= 3 ? 'broad' : brief.consistency <= 7 ? 'balanced' : 'high precision'})
- Campaign description: ${brief.description}

IMPORTANT: Write the ENTIRE report in ${reportLang}. Every heading, label, table header, bullet point, and sentence must be in ${reportLang}. Do not switch languages under any circumstance. Use markdown formatting with professional headers, bullet points, bold text, and tables where appropriate.

Structure the report as follows — DO NOT include JSON, only clean markdown:

---

# 📊 Campaign Intelligence Report

## Executive Summary
[2-3 sentences summarizing the campaign objective and strategic opportunity]

---

## 🎯 Objective Analysis
[Analyze the user's specific goal, business/personal context, and what they want to achieve. Be precise and insightful.]

---

## 👤 Ideal Contact Profile
[Describe the optimal contact profile based on the filters selected. Include typical roles, seniority, specializations, and organizational types.]

| Attribute | Profile |
|---|---|
| Sector | ... |
| Decision Level | ... |
| Engagement Type | ... |
| Response Likelihood | ... |

---

## 🔍 Search & Discovery Strategy
[Explain how the extension will approach the search: what platforms, directories, methods. Be specific to the affinity domain.]

**What the extension WILL do:**
- ...

**What the extension WILL NOT do:**
- ...

---

## 📈 Affinity Relevance Assessment
[Assess how well the selected affinity category (${brief.affinityCategory} > ${brief.affinitySubcategory}) aligns with the goal. Score each dimension:]

| Dimension | Score | Rationale |
|---|---|---|
| Domain Alignment | X/10 | ... |
| Contact Availability | X/10 | ... |
| Response Probability | X/10 | ... |
| Geographic Reach | X/10 | ... |

---

## ⚙️ Execution Process
[Step-by-step process flow for how this campaign will execute]

1. **Phase 1 — Analysis** (...)
2. **Phase 2 — Discovery** (...)
3. **Phase 3 — Enrichment** (...)
4. **Phase 4 — Outreach** (...)

---

## 📊 Expected Outcomes
[Realistic projections based on the precision level ${brief.consistency}/10 and the selected niche]

| Metric | Estimate |
|---|---|
| Contacts Discovered | ... |
| Relevant Matches | ... |
| Outreach Candidates | ... |
| Expected Response Rate | ... |

---

## 💡 Strategic Recommendations
[3-5 specific, actionable recommendations to maximize campaign success]

---

*Report generated by Vibe Reach AI · ${new Date().toLocaleDateString()}*`
}

function buildAnalysisPrompt(userPrompt: string, consistency: number): string {
  return `You are an investigative research assistant. Analyze this objective and create a structured plan.

Objective: ${userPrompt}

Search precision level: ${consistency}/10 (1=very broad, 10=extremely strict)

Respond ONLY with valid JSON:
{
  "problemAnalysis": "brief analysis of the problem",
  "strategy": "recommended investigation strategy",
  "targetAudiences": ["audience1", "audience2"],
  "suggestedSources": ["source1", "source2"],
  "expectedContactTypes": ["type1", "type2"]
}`
}

function buildMessagePrompt(contact: Contact, context: string): string {
  const hasForm = contact.contactMethod === 'form' || contact.contactMethod === 'both'
  const formFieldHint = contact.formFields?.length
    ? `\nDETECTED FORM FIELDS: ${contact.formFields.map((f) => `${f.name} (${f.type}${f.required ? ', required' : ''})`).join(', ')}`
    : ''
  const domainHint = contact.domainMeta
    ? `\nWEBSITE CONTEXT: "${contact.domainMeta.title}" — ${contact.domainMeta.description}`
    : ''

  // context may optionally carry a SENDER: block appended by the UI
  return `You are an expert business writer. Write a first-contact outreach message that feels personal, elegant, and completely human — not a template.

RECIPIENT:
- Organization: ${contact.organization || contact.name}
- Role: ${contact.role || 'Professional'}
- Specialization: ${contact.specialization}
- Topics: ${contact.topics.join(', ')}
- Region: ${contact.region}
- Website: ${contact.website}
- Contact method: ${contact.contactMethod || 'email'}
- Affinity score: ${contact.relevanceScore}/100${domainHint}${formFieldHint}

CAMPAIGN PURPOSE / SENDER INFO:
${context}

${hasForm ? `PRIMARY OUTPUT: contactFormMessage — this is the MAIN message because the recipient has a web contact form.
The message should be complete and self-contained (2-4 sentences), professional and collaborative.
If form fields are listed above, also provide formFieldMapping that maps your content to those field names.` : `PRIMARY OUTPUT: emailBody — the recipient will be contacted by email.`}

FIELDS TO PRODUCE (JSON):
  emailSubject  → max 8 words, specific to the recipient's work, never generic
  emailBody     → a complete, ready-to-send plain-text email with this layout:

      Estimado/a [appropriate salutation based on role],

      [Intro — 2-3 sentences: reference something concrete about their work/site,
       show genuine knowledge of what they do.]

      [Middle — 2-3 sentences: who the sender is, what they offer, and
       why it connects to the recipient's world. Confident, not salesy.]

      [Closing — 1-2 sentences: one soft CTA — a brief call, a reply,
       or an exchange; easy to say yes to.]

      Atentamente,

      [Sender name or company name from SENDER INFO]
      [Sender email from SENDER INFO — omit if empty]
      [Sender phone from SENDER INFO — omit if empty]

  contactFormMessage → 2-4 sentence version for web contact forms (no greeting/signature needed).
                       Must be self-contained and professional. Reference something specific about
                       the recipient's site/work to show it's not mass-sent.
  followUpMessage    → 2-3 sentence gentle nudge for one week later, assuming no reply
  formFieldMapping   → (optional) JSON object mapping form field names to the text that should
                       fill each field, e.g. {"nombre": "...", "email": "...", "mensaje": "..."}

TONE RULES:
- Language: Spanish by default; English if recipient region is clearly non-Spanish-speaking
- NEVER use: "espero que estés bien", "no dudes en contactarme", "sinergia", "leveraging"
- Affinity ≥ 80: slightly warmer, reference a specific aspect of their focus area
- Total body word count (excluding signature): 100-150 words
- Reads like a real thoughtful person wrote it, not a CRM blast

Respond ONLY with valid JSON (no markdown wrapper):
{
  "emailSubject": "...",
  "emailBody": "...",
  "contactFormMessage": "...",
  "followUpMessage": "..."${hasForm ? ',\n  "formFieldMapping": {}' : ''}
}`
}

function buildTargetDiscoveryPrompt(brief: CampaignBrief): string {
  const contactDesc =
    brief.contactType === 'corporate'
      ? 'companies and businesses'
      : brief.contactType === 'individual'
        ? 'individual professionals, freelancers and consultants'
        : 'NGOs, institutions, public organizations and associations'
  return `You are a professional web researcher with deep knowledge of online directories, industry portals, and business databases.

Your task: generate a list of 10-15 REAL, currently active websites where ${contactDesc} related to "${brief.affinityCategory}" (specifically "${brief.affinitySubcategory}") in "${brief.country}" can be found.

Campaign objective: ${brief.description}

REQUIREMENTS for each target URL:
- Must be a real, existing, publicly accessible website
- Must list or feature organizations/individuals with publicly visible contact info
- Should be relevant to ${brief.affinityCategory} / ${brief.affinitySubcategory} in ${brief.country}
- Include a mix of types: industry directories, sector portals, association registers, media outlets, blogs

IMPORTANT: Only include websites you are confident exist. Do not invent URLs.

Respond ONLY with valid JSON (no markdown, no explanation outside the JSON):
{
  "targets": [
    {
      "url": "https://example-directory.com/members",
      "domain": "example-directory.com",
      "rationale": "National membership directory for ${brief.affinitySubcategory} professionals in ${brief.country}",
      "type": "directory",
      "estimatedContacts": 15
    }
  ]
}`
}

function buildSearchCriteriaPrompt(brief: CampaignBrief): string {
  const contactDesc =
    brief.contactType === 'corporate'
      ? 'empresas y negocios'
      : brief.contactType === 'individual'
        ? 'profesionales independientes y consultores'
        : 'ONGs, instituciones, organizaciones públicas y asociaciones'
  return `You are a search strategist. Your task is to generate families of search engine queries that will help discover ${contactDesc} related to "${brief.affinityCategory}" (specifically "${brief.affinitySubcategory}") in "${brief.country}".

Campaign objective: ${brief.description}
Language: ${brief.language}
Precision level: ${brief.consistency}/10 (${brief.consistency <= 3 ? 'broad' : brief.consistency <= 7 ? 'balanced' : 'high precision'})

CRITICAL RULES:
1. Generate ONLY search queries (strings to type into Google/Bing). NEVER output domain names, URLs, or website addresses.
2. Each query family should target a different angle: industry directories, professional associations, regional listings, niche portals, etc.
3. Include the word "contacto", "formulario", or "contact" in at least half of the queries to bias results toward pages with contact forms.
4. Queries should be in ${brief.language} (matching the target market).
5. Generate ${brief.consistency >= 7 ? '6-8' : '4-6'} families with 3-5 queries each.
6. Higher priority families (lower number) should target more specific/niche queries.

Respond ONLY with valid JSON (no markdown):
{
  "families": [
    {
      "category": "descriptive label for this group",
      "queries": ["query 1", "query 2", "query 3"],
      "rationale": "why this family is relevant",
      "priority": 1
    }
  ],
  "estimatedReach": 50
}`
}

function parseJSON<T>(text: string): T {
  const match = text.match(/\{[\s\S]*\}/)
  if (!match) throw new Error('No JSON found in response')
  return JSON.parse(match[0]) as T
}

// ── OpenAI Provider ──
function createOpenAIProvider(apiKey: string, model: string): AIProvider {
  async function call(messages: { role: string; content: string }[], plain = false) {
    const res = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify({ model, messages, temperature: plain ? 0.9 : 0.7 }),
    })
    if (!res.ok) throw new Error(`OpenAI API error: ${res.status}`)
    const data = await res.json()
    return data.choices[0].message.content as string
  }

  return {
    async analyzeCampaign(brief) {
      try {
        const content = await call(
          [{ role: 'user', content: buildCampaignReportPrompt(brief) }],
          true,
        )
        return { success: true, data: { reportMarkdown: content } }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async analyzePrompt(prompt, consistency) {
      try {
        const content = await call([
          { role: 'user', content: buildAnalysisPrompt(prompt, consistency) },
        ])
        return { success: true, data: parseJSON<AIAnalysisResult>(content) }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async generateMessages(contact, context) {
      try {
        const content = await call([
          { role: 'user', content: buildMessagePrompt(contact, context) },
        ])
        return { success: true, data: parseJSON<AIMessageResult>(content) }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async generateSearchTargets(brief) {
      try {
        const content = await call([{ role: 'user', content: buildTargetDiscoveryPrompt(brief) }])
        return { success: true, data: parseJSON<TargetDiscoveryResult>(content) }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async generateSearchCriteria(brief) {
      try {
        const content = await call([{ role: 'user', content: buildSearchCriteriaPrompt(brief) }])
        return { success: true, data: parseJSON<AISearchCriteriaResult>(content) }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async testConnection() {
      try {
        const res = await fetch('https://api.openai.com/v1/models', {
          headers: { Authorization: `Bearer ${apiKey}` },
        })
        if (!res.ok) throw new Error(`Status ${res.status}`)
        return { success: true, data: { model } }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async evaluate(prompt) {
      try {
        const content = await call([{ role: 'user', content: prompt }])
        return { success: true, data: content }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
  }
}

// ── Grok (xAI) Provider — OpenAI-compatible ──
function createGrokProvider(apiKey: string, model: string): AIProvider {
  async function call(messages: { role: string; content: string }[], plain = false) {
    const res = await fetch('https://api.x.ai/v1/chat/completions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify({ model, messages, temperature: plain ? 0.9 : 0.7 }),
    })
    if (!res.ok) throw new Error(`Grok API error: ${res.status}`)
    const data = await res.json()
    return data.choices[0].message.content as string
  }

  return {
    async analyzeCampaign(brief) {
      try {
        const content = await call(
          [{ role: 'user', content: buildCampaignReportPrompt(brief) }],
          true,
        )
        return { success: true, data: { reportMarkdown: content } }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async analyzePrompt(prompt, consistency) {
      try {
        const content = await call([
          { role: 'user', content: buildAnalysisPrompt(prompt, consistency) },
        ])
        return { success: true, data: parseJSON<AIAnalysisResult>(content) }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async generateMessages(contact, context) {
      try {
        const content = await call([
          { role: 'user', content: buildMessagePrompt(contact, context) },
        ])
        return { success: true, data: parseJSON<AIMessageResult>(content) }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async generateSearchTargets(brief) {
      try {
        const content = await call([{ role: 'user', content: buildTargetDiscoveryPrompt(brief) }])
        return { success: true, data: parseJSON<TargetDiscoveryResult>(content) }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async generateSearchCriteria(brief) {
      try {
        const content = await call([{ role: 'user', content: buildSearchCriteriaPrompt(brief) }])
        return { success: true, data: parseJSON<AISearchCriteriaResult>(content) }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async testConnection() {
      try {
        const res = await fetch('https://api.x.ai/v1/models', {
          headers: { Authorization: `Bearer ${apiKey}` },
        })
        if (!res.ok) throw new Error(`Status ${res.status}`)
        return { success: true, data: { model } }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async evaluate(prompt) {
      try {
        const content = await call([{ role: 'user', content: prompt }])
        return { success: true, data: content }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
  }
}

// ── Google AI (Gemini) Provider ──
function createGoogleProvider(apiKey: string, model: string): AIProvider {
  const base = 'https://generativelanguage.googleapis.com/v1beta'

  async function call(prompt: string) {
    const res = await fetch(`${base}/models/${model}:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] }),
    })
    if (!res.ok) throw new Error(`Google AI error: ${res.status}`)
    const data = await res.json()
    return data.candidates[0].content.parts[0].text as string
  }

  return {
    async analyzeCampaign(brief) {
      try {
        const content = await call(buildCampaignReportPrompt(brief))
        return { success: true, data: { reportMarkdown: content } }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async analyzePrompt(prompt, consistency) {
      try {
        const content = await call(buildAnalysisPrompt(prompt, consistency))
        return { success: true, data: parseJSON<AIAnalysisResult>(content) }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async generateMessages(contact, context) {
      try {
        const content = await call(buildMessagePrompt(contact, context))
        return { success: true, data: parseJSON<AIMessageResult>(content) }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async generateSearchTargets(brief) {
      try {
        const content = await call(buildTargetDiscoveryPrompt(brief))
        return { success: true, data: parseJSON<TargetDiscoveryResult>(content) }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async generateSearchCriteria(brief) {
      try {
        const content = await call(buildSearchCriteriaPrompt(brief))
        return { success: true, data: parseJSON<AISearchCriteriaResult>(content) }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async testConnection() {
      try {
        const res = await fetch(`${base}/models?key=${apiKey}`)
        if (!res.ok) throw new Error(`Status ${res.status}`)
        return { success: true, data: { model } }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
    async evaluate(prompt) {
      try {
        const content = await call(prompt)
        return { success: true, data: content }
      } catch (e) {
        return { success: false, error: (e as Error).message }
      }
    },
  }
}

// ── Factory ──
export function createAIProvider(type: AIProviderType, apiKey: string, model: string): AIProvider {
  switch (type) {
    case 'openai':
      return createOpenAIProvider(apiKey, model)
    case 'grok':
      return createGrokProvider(apiKey, model)
    case 'google':
      return createGoogleProvider(apiKey, model)
  }
}
